### ISSUE TITLE
Fancy chart around inlinable_string and maps

### ISSUE THREAD

**Issue by ArtemGr** [fitzgen/inlinable_string#9]
First, I'm going to learn to ggplot soon ([cf](https://www.reddit.com/r/rust/comments/630ce7/what_should_a_graph_plotting_and_data/)).
Second, I want an actual information regarding the current speed of promising map implementations (e.g. BTreeMap, OrderMap) with and without inlinable_string.

So I'd like to write a little program that would benchmark some map implementations, generating a plot that we could put in the inlinable_string README or something.
(For example, https://github.com/facebook/zstd has this plot in the README: https://raw.githubusercontent.com/facebook/zstd/dev/doc/images/Cspeed4.png).

- [x] Experiment with ggplot2, see if I can use it to plot the charts.
- [ ] ...

@fitzgen Nick, would it be okay to host that inlinable_string benchmarking script inside the inlinable_string repository?

**Comment by fitzgen** [comment]
> host that inlinable_string benchmarking script inside the inlinable_string repository?

Yep, that sounds great! I'm all for reproducibility ;)

**Comment by ArtemGr** [comment]
Speaking of reproducibility, it would be nice to generate a sort of an ASCII chart by default, to make benchmark results accessible *anywhere*. Generating a ggplot script would be a secondary option then.

**Comment by ArtemGr** [comment]
Turns out I have lots of urgent stuff to do, so closing this one for now.
